version: v2beta1
name: minimal-app

vars:
  APP_PORT:
    source: env
    default: "9090"
  ENVIRONMENT:
    source: env
    default: "development"

pipelines:
  dev:
    run: |-
      run_dependencies --all
      create_deployments --all
      start_dev app
  
  deploy:
    run: |-
      run_dependencies --all
      build_images --all -t $(git describe --always)
      create_deployments --all

images:
  app:
    image: my-registry/minimal-app
    dockerfile: ./Dockerfile

deployments:
  app:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
        - image: my-registry/minimal-app
          env:
          - name: PORT
            value: "${APP_PORT}"
          - name: ENVIRONMENT
            value: "${ENVIRONMENT}"
        service:
          ports:
          - port: ${APP_PORT}

dev:
  app:
    imageSelector: my-registry/minimal-app
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.24-alpine
    # devImage: docker.io/pallewela/golang-tools:1.26-alpine
    ports:
    - port: "${APP_PORT}:${APP_PORT}"
    open:
    - url: http://localhost:${APP_PORT}
    terminal:
      command: sh ./devspace_start.sh
      #command: sh 
    sync:
    - path: ./
      excludePaths:
      - .git/
      - .devspace/
      - '*.log'
